on:
  workflow_dispatch:
name: Deploy Azure Resources
permissions:
    id-token: write
    contents: read
jobs:
    deploy-and-configure-azure:
      runs-on: ubuntu-latest
      steps:
  
        # Checkout code
      - uses: actions/checkout@main
        name: 'Checkout code'
  
        # Log into Azure
      - uses: azure/login@v2
        name: 'Azure Login'
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # Deploy Bicep templates
      - name: Deploy Resources
        id: deploy
        uses: azure/arm-deploy@v2
        with:
            scope: 'subscription'
            region: 'UK South'
            resourceGroupName: ${{ secrets.AZURE_RG }}
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            parameters: 'resourceGroupName=${{ secrets.AZURE_RG }}'
            template: ./main.bicep